package(
  default_visibility = ["//visibility:public"],
)

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
  name = "pellscript",
  srcs = [
    "ast_nodes.h",
    "lexer.cpp",
    "lexer.h",
    "main.cpp",
    "parser.cpp",
    "parser.h",
  ],
)