package(
  default_visibility = ["//visibility:public"],
)

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
  name = "pellscript",
  srcs = [
    "main.cpp",
    "lexer.cpp",
    "lexer.h",
  ],
)